name: Dependency Vulnerability Audit

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
            - cron: '0 0 * * 0'

jobs:
    vulnerability_audit:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            subdir: [isotomachine, isototest]

        steps:
            - uses: actions/checkout@v3

            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true

            - name: Install libvnc as dependency
              run: sudo apt-get update && sudo apt-get install -y libvncserver-dev

            - name: Run cargo audit in ${{ matrix.subdir }}
              working-directory: ${{ matrix.subdir }}
              run: cargo audit --color always
