name: Execute Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subdir: [isotomachine, isototest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install libvncserver-devel as dependency
        run: sudo apt-get update && sudo apt-get install -y libvncserver-dev

      - name: Run Cargo test
        working-directory: ${{ matrix.subdir }}
        run: cargo test --verbose
